#!/bin/bash

# Script d'aide rapide pour Capacitor
# Affiche les commandes les plus utiles

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         QR Event - Commandes Capacitor Rapides            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 GÉNÉRATION D'APK"
echo "  ./build-apk.sh"
echo "    → Génère automatiquement l'APK de debug"
echo ""
echo "🔨 BUILD & SYNC"
echo "  npm run build"
echo "    → Compile l'application React"
echo ""
echo "  npm run cap:sync"
echo "    → Synchronise les fichiers avec Android"
echo ""
echo "  npm run cap:build"
echo "    → Build + Sync en une commande"
echo ""
echo "🛠️  ANDROID STUDIO"
echo "  npm run cap:open:android"
echo "    → Ouvre le projet dans Android Studio"
echo ""
echo "📱 GRADLE (depuis le dossier android/)"
echo "  cd android"
echo "  ./gradlew assembleDebug"
echo "    → Génère l'APK de debug"
echo ""
echo "  ./gradlew assembleRelease"
echo "    → Génère l'APK de production (nécessite signature)"
echo ""
echo "  ./gradlew clean"
echo "    → Nettoie le build"
echo ""
echo "📍 LOCALISATION DE L'APK"
echo "  android/app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "📚 DOCUMENTATION"
echo "  cat CAPACITOR_SETUP_COMPLETE.md"
echo "    → Résumé de la configuration"
echo ""
echo "  cat BUILD_APK_GUIDE.md"
echo "    → Guide complet de génération d'APK"
echo ""
echo "  cat android/README.md"
echo "    → Documentation du projet Android"
echo ""
echo "🔧 INSTALLATION DE JAVA (si nécessaire)"
echo "  sudo apt update"
echo "  sudo apt install openjdk-17-jdk"
echo "  export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
echo ""
echo "═══════════════════════════════════════════════════════════"
echo ""
