### Validation d'un QR Code complet
POST http://localhost:3001/api/events/68f24a11b8df2f1fafe1dd57/validate-qr-full
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjIyNmEzNDI3NDg4YzQxMmUwYTVlZSIsInJvbGUiOiJhZG1pbmlzdHJhdGV1ciIsImlhdCI6MTc2MDg3Nzg0OSwiZXhwIjoxNzYxNDgyNjQ5fQ.blsNHEg7BOsFVa1C04TXjC52ZnDYMc8rHW9EZWs9nuQ

{
  "qrData": {
    "eventId": "68f24a11b8df2f1fafe1dd57",
    "participantId": "68f4e8a67607df26eb07a305",
    "eventName":"Hackathon 2025"
  }
}
